# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
name = "banner-disount"
handle = "banner-disount"
type = "ui_extension"
uid = "6a32ffa1-8259-216f-fafe-841f4dc831edb0a7784d"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "banner_title"
type = "single_line_text_field"
name = "Banner title"
description = "Enter a title for the banner"

[[extensions.settings.fields]]
key = "banner_image_url"
type = "single_line_text_field"
name = "Banner Image URL"
description = "Enter the full URL of the banner image"

[[extensions.settings.fields]]
key = "button_text"
type = "single_line_text_field"
name = "Button Text"
description = "Text for the call-to-action button"
default = "Claim Free Gift"

[[extensions.settings.fields]]
key = "checkbox_text"
type = "single_line_text_field"
name = "Checkbox Text"
description = "Text for the checkbox label"
default = "I want a free gift"

[[extensions.settings.fields]]
key = "free_product_variant_id"
type = "single_line_text_field"
name = "Free Product Variant ID"
description = "GID of the product variant to add as free gift"
default = "gid://shopify/ProductVariant/1234567890"